#!/usr/bin/env python3
"""
YouTube Cookie Refresher — Run locally to export fresh cookies for the bot.

This opens a browser window where you log into YouTube manually.
After login, it exports cookies in Netscape format for yt-dlp.

Usage:
    pip install playwright
    playwright install chromium
    python refresh_cookies.py

The exported cookies.txt can be:
  1. Pasted into Render's YOUTUBE_COOKIES environment variable
  2. Sent to the bot as a file, then replied to with /setcookies
"""

import asyncio
import sys
from pathlib import Path

try:
    from playwright.async_api import async_playwright
except ImportError:
    print("❌ Playwright is not installed.")
    print()
    print("   Install it with:")
    print("     pip install playwright")
    print("     playwright install chromium")
    sys.exit(1)


def cookies_to_netscape(cookies: list) -> str:
    """Convert Playwright cookies to Netscape cookies.txt format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by refresh_cookies.py",
        "# https://curl.se/docs/http-cookies.html",
        "",
    ]
    for cookie in cookies:
        domain = cookie.get("domain", "")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = cookie.get("path", "/")
        secure = "TRUE" if cookie.get("secure", False) else "FALSE"
        expiry = str(int(cookie.get("expires", 0)))
        name = cookie.get("name", "")
        value = cookie.get("value", "")
        lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


async def main():
    print()
    print("=" * 50)
    print("  🍪 YouTube Cookie Refresher")
    print("=" * 50)
    print()
    print("  A browser window will open.")
    print("  1. Log into YouTube with your dedicated account")
    print("  2. Wait until you see the YouTube homepage")
    print("  3. Come back here and press Enter")
    print()

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/131.0.0.0 Safari/537.36"
            )
        )
        page = await context.new_page()

        # Navigate to Google login for YouTube
        await page.goto(
            "https://accounts.google.com/ServiceLogin"
            "?service=youtube"
            "&continue=https://www.youtube.com/"
        )

        print("  🌐 Browser opened — please log into YouTube now...")
        print()
        input("  Press Enter after you're logged in and see YouTube → ")
        print()

        # Navigate to YouTube to ensure all cookies are captured
        print("  📡 Capturing YouTube cookies...")
        await page.goto("https://www.youtube.com")

        try:
            await page.wait_for_load_state("networkidle", timeout=15000)
        except Exception:
            pass  # Timeout is fine, cookies should be set by now

        # Get all cookies from the browser context
        cookies = await context.cookies()

        # Filter to YouTube/Google-related cookies only
        yt_cookies = [
            c for c in cookies
            if any(
                d in c.get("domain", "")
                for d in ["youtube.com", "google.com", "googlevideo.com"]
            )
        ]

        if not yt_cookies:
            print("  ❌ No YouTube cookies found!")
            print("     Make sure you logged in successfully.")
            await browser.close()
            return

        netscape_content = cookies_to_netscape(yt_cookies)

        # Save to cookies.txt in the current directory
        output_file = Path("cookies.txt")
        output_file.write_text(netscape_content, encoding="utf-8")

        print(f"  ✅ Exported {len(yt_cookies)} cookies to: {output_file.absolute()}")
        print()
        print("  " + "─" * 46)
        print("  Next steps — pick one:")
        print("  " + "─" * 46)
        print()
        print("  Option A — Render Dashboard:")
        print("    1. Open cookies.txt and copy ALL contents")
        print("    2. Go to Render → your service → Environment")
        print("    3. Set YOUTUBE_COOKIES = (paste contents)")
        print("    4. Save → Render auto-redeploys with fresh cookies")
        print()
        print("  Option B — Telegram Bot:")
        print("    1. Send cookies.txt as a file to your bot (DM)")
        print("    2. Reply to that file message with /setcookies")
        print()

        await browser.close()


if __name__ == "__main__":
    asyncio.run(main())
