#!/usr/bin/env python3
"""
Automated YouTube Cookie Refresher — Playwright Persistent Session Engine.

Features:
1. Automated background cookie extraction (headless) for Windows Task Scheduler.
2. One-time interactive browser login (`python refresh_cookies.py --login`).
3. Auto-pushes updated cookies to Render API (`YOUTUBE_COOKIES`) and triggers a redeploy.

Usage:
    python refresh_cookies.py           # Auto-refresh using stored profile & push to Render
    python refresh_cookies.py --login   # Open browser window to log into YouTube (1-time setup)
    python refresh_cookies.py --no-push # Refresh cookies locally without pushing to Render

Requirements:
    pip install playwright requests python-dotenv
    python -m playwright install chromium
"""

import sys
import os
import asyncio
import argparse
from pathlib import Path

# Fix Windows console encoding for emoji support
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# ── Dependency checks ────────────────────────────────────────────────────────
missing = []
try:
    import requests
except ImportError:
    missing.append("requests")

try:
    import playwright
except ImportError:
    missing.append("playwright")

if missing:
    print(f"❌ Missing packages: {', '.join(missing)}")
    print(f"   Run: pip install {' '.join(missing)}")
    sys.exit(1)

# Load .env if available
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# ── Configuration ─────────────────────────────────────────────────────────────
RENDER_API_KEY    = os.getenv("RENDER_API_KEY", "")
RENDER_SERVICE_ID = os.getenv("RENDER_SERVICE_ID", "")
PROFILE_DIR       = Path(__file__).parent.resolve() / ".browser_profile"


# ── Cookie formatting & extraction ───────────────────────────────────────────

def playwright_cookies_to_netscape(cookies: list) -> tuple[str, int]:
    """Convert Playwright cookies array to Netscape cookies.txt format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by refresh_cookies.py (Playwright)",
        "# https://curl.se/docs/http-cookies.html",
        "",
    ]
    count = 0
    for c in cookies:
        domain = c.get("domain", "")
        if any(d in domain for d in ["youtube.com", "google.com", "googlevideo.com"]):
            include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.get("path", "/")
            secure = "TRUE" if c.get("secure", False) else "FALSE"
            expires_val = c.get("expires", 0)
            expiry = str(int(expires_val)) if expires_val and expires_val > 0 else "0"
            name = c.get("name", "")
            value = c.get("value", "")
            lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
            count += 1
    return "\n".join(lines) + "\n", count


async def extract_cookies_playwright(headless: bool = True, force_login: bool = False) -> tuple[str, int]:
    """
    Extract YouTube cookies using Playwright persistent browser context.
    If session is not authenticated or force_login=True, opens browser window for user login.
    """
    from playwright.async_api import async_playwright

    PROFILE_DIR.mkdir(exist_ok=True)

    async with async_playwright() as p:
        print("  📂  Opening persistent browser session...")
        context = await p.chromium.launch_persistent_context(
            user_data_dir=str(PROFILE_DIR),
            headless=headless if not force_login else False,
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/131.0.0.0 Safari/537.36"
            ),
            args=["--disable-blink-features=AutomationControlled"]
        )

        page = context.pages[0] if context.pages else await context.new_page()

        try:
            await page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=25000)
        except Exception as e:
            print(f"  ⚠️   Page navigation warning: {e}")

        cookies = await context.cookies()

        # Check if logged in (look for SAPISID, __Secure-3PAPISID, or LOGIN_INFO)
        has_auth = any(c.get("name") in ["SAPISID", "__Secure-3PAPISID", "LOGIN_INFO", "SID"] for c in cookies)

        if force_login or not has_auth:
            if headless and not force_login:
                print("  🔒  No active YouTube session found in profile.")
                await context.close()
                return await extract_cookies_playwright(headless=False, force_login=True)

            print()
            print("  🌐  Opening Google Login window for YouTube...")
            print("  ──────────────────────────────────────────────────")
            print("  1. Log into your YouTube account in the opened browser window.")
            print("  2. Wait until you see the YouTube home page.")
            print("  ──────────────────────────────────────────────────")
            print()
            await page.goto(
                "https://accounts.google.com/ServiceLogin?service=youtube&continue=https://www.youtube.com/",
                wait_until="domcontentloaded"
            )

            # Wait for user input in console
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(None, input, "  👉  Press Enter after you have finished logging in... ")
            print()

            try:
                await page.goto("https://www.youtube.com", wait_until="networkidle", timeout=15000)
            except Exception:
                pass

            cookies = await context.cookies()

        netscape_content, count = playwright_cookies_to_netscape(cookies)
        await context.close()
        return netscape_content, count


# ── Render API ────────────────────────────────────────────────────────────────

def push_cookies_to_render(cookie_content: str) -> bool:
    """Update YOUTUBE_COOKIES on Render and trigger a redeploy."""

    if not RENDER_API_KEY or not RENDER_SERVICE_ID:
        print()
        print("  ⚠️   Render credentials not set in .env — skipping auto-push.")
        print("  Add these to your .env file:")
        print("    RENDER_API_KEY=rnd_xxxx")
        print("    RENDER_SERVICE_ID=srv-xxxx")
        print()
        return False

    headers = {
        "Authorization": f"Bearer {RENDER_API_KEY}",
        "Content-Type": "application/json",
    }

    # Step 1: Fetch existing env vars to preserve TELEGRAM_BOT_TOKEN and others
    print("  📤  Fetching existing Render env vars to preserve settings...")
    env_vars_map = {}

    # Read from local .env as fallback baseline
    for key in ["TELEGRAM_BOT_TOKEN", "OPENROUTER_API_KEY", "ADMIN_USER_IDS", "PORT"]:
        val = os.getenv(key)
        if val:
            env_vars_map[key] = val

    try:
        get_resp = requests.get(
            f"https://api.render.com/v1/services/{RENDER_SERVICE_ID}/env-vars",
            headers=headers,
            timeout=15,
        )
        if get_resp.status_code == 200:
            for item in get_resp.json():
                ev = item.get("envVar", {}) if isinstance(item, dict) else {}
                k = ev.get("key")
                v = ev.get("value")
                if k:
                    env_vars_map[k] = v
    except Exception as e:
        print(f"  ⚠️   Could not fetch existing env vars: {e}")

    # Set / overwrite YOUTUBE_COOKIES
    env_vars_map["YOUTUBE_COOKIES"] = cookie_content

    payload = [{"key": k, "value": v} for k, v in env_vars_map.items()]

    print(f"  📤  Pushing {len(payload)} environment variables to Render...")
    resp = requests.put(
        f"https://api.render.com/v1/services/{RENDER_SERVICE_ID}/env-vars",
        headers=headers,
        json=payload,
        timeout=15,
    )

    if resp.status_code not in (200, 201):
        print(f"  ❌  Failed to update env vars ({resp.status_code}): {resp.text[:200]}")
        return False

    print("  ✅  YOUTUBE_COOKIES and environment variables updated on Render!")

    # Step 2: Trigger redeploy so bot picks up the new cookies
    print("  🚀  Triggering Render redeploy...")
    resp = requests.post(
        f"https://api.render.com/v1/services/{RENDER_SERVICE_ID}/deploys",
        headers=headers,
        json={"clearCache": "do_not_clear"},
        timeout=15,
    )

    if resp.status_code in (200, 201):
        print("  ✅  Redeploy triggered! Bot will have fresh cookies in ~1-2 min.")
        return True
    else:
        print(f"  ⚠️   Redeploy trigger failed ({resp.status_code}) — but cookies were saved.")
        return True


# ── Main ──────────────────────────────────────────────────────────────────────

async def main_async():
    parser = argparse.ArgumentParser(
        description="Refresh YouTube cookies and push to Render"
    )
    parser.add_argument(
        "--login", action="store_true",
        help="Open visible browser window to log into YouTube (1-time setup)"
    )
    parser.add_argument(
        "--no-push", action="store_true",
        help="Extract cookies locally but don't push to Render"
    )
    args = parser.parse_args()

    print()
    print("=" * 55)
    print("  🍪  YouTube Cookie Refresher (Playwright Engine)")
    print("=" * 55)
    print()
    print(f"  Mode    : {'Interactive Login (--login)' if args.login else 'Automated Refresh'}")
    print(f"  Push    : {'Disabled (--no-push)' if args.no_push else 'Render API'}")
    print()

    try:
        netscape_content, count = await extract_cookies_playwright(
            headless=not args.login,
            force_login=args.login
        )

        if count == 0:
            print("  ❌  No YouTube cookies found!")
            print("  Run with --login to log into YouTube once:")
            print("    python refresh_cookies.py --login")
            sys.exit(1)

        print(f"  ✅  Extracted {count} YouTube cookies.")
        print()

        # Save local cookies.txt copy
        output_file = Path("cookies.txt")
        output_file.write_text(netscape_content, encoding="utf-8")
        print(f"  💾  Saved to {output_file.absolute()}")

        if args.no_push:
            print()
            print("  --no-push: Skipping Render push.")
        else:
            print()
            push_cookies_to_render(cookie_content=netscape_content)

    except Exception as e:
        print(f"\n  ❌  Error during cookie refresh: {e}")
        sys.exit(1)

    print()
    print("─" * 55)
    print("  Task Scheduler: Runs every 5 days automatically.")
    print("─" * 55)
    print()


if __name__ == "__main__":
    asyncio.run(main_async())
